version: "3"

services:
  orrery:
    container_name: orrery-cont
    image: orrery-space-apps:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - 3000:5050
