<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/krunker_prp/Projects/orrery-space-apps/static/models/scene.gltf --root /models/ --types --printwidth 120 --precision 2
Author: valmirt (https://sketchfab.com/valmirt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-system-d3f058bbe20e4f70b2b52277ff8e109a
Title: Solar System
-->

<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import { OrbitControls, MeshLineGeometry, MeshLineMaterial, FakeGlowMaterial } from '@threlte/extras'
  import {CuerpoCeleste} from '../../propagate-kepler'
  import { Vector3 } from 'three'
  import { TextureLoader } from 'three'
  import { useLoader } from '@threlte/core'
  import type { AsyncWritable } from '@threlte/core';    
  import { Texture } from 'three';

  const textureSun = useLoader(TextureLoader).load('/models/textures/lambert2_baseColor.jpeg')
  const textureMercury = useLoader(TextureLoader).load('/models/textures/lambert3_baseColor.jpeg')
  const textureVenus = useLoader(TextureLoader).load('/models/textures/lambert4_baseColor.jpeg')
  const textureEarth = useLoader(TextureLoader).load('/models/textures/lambert5_baseColor.jpeg')
  const textureMars = useLoader(TextureLoader).load('/models/textures/lambert6_baseColor.jpeg')
  const textureJupyter = useLoader(TextureLoader).load('/models/textures/lambert7_baseColor.jpeg')
  const textureSaturn = useLoader(TextureLoader).load('/models/textures/lambert9_baseColor.jpeg')
  const textureUranus = useLoader(TextureLoader).load('/models/textures/lambert10_baseColor.jpeg')
  const textureNeptune = useLoader(TextureLoader).load('/models/textures/lambert11_baseColor.png')
  const texturePluto = useLoader(TextureLoader).load('/models/textures/lambert12_baseColor.jpeg')
  const textureSaturnR = useLoader(TextureLoader).load('/models/textures/lambert13_baseColor.jpeg')

  

  const mercurio = new CuerpoCeleste("Mercurio", 0.38709927, 0.00000037,
      0.20563593, 0.00001906, 7.00497902, -0.00594749, 252.25032350,
      149472.67411175, 77.45779628, 0.16047689, 48.33076593, -0.12534081, 0.240846,textureMercury);
  const venus = new CuerpoCeleste("Venus", 0.72333566, 0.00000390, 0.00677672,
      -0.00004107, 3.39467605, -0.00078890, 181.97909950, 58517.81538729,
      131.60246718, 0.00268329, 76.67984255, -0.27769418, 0.615,textureVenus);
  const tierra = new CuerpoCeleste("Tierra", 1.00000261, 0.00000562, 0.01671123,
      -0.00004392, -0.00001531, -0.01294668, 100.46457166, 35999.37244981,
      102.93768193, 0.32327364, 0, 0, 1,textureEarth);
  const marte = new CuerpoCeleste("Marte", 1.52371243, 0.00000097, 0.09336511, 0.00009149, 1.85181869, -0.00724757, -4.56813164, 19140.29934243, -23.91744784, 0.45223625, 49.71320984, -0.26852431, 1.881,textureMars);
  const jupiter = new CuerpoCeleste("Júpiter", 5.20288700, -0.00011607,
      0.04838624, -0.00013253, 1.30439695, -0.00183714, 34.39644051, 3034.74612775,
      14.72847983, 0.21252668, 100.47390909, 0.20469106, 11.86,textureJupyter);
  const saturno = new CuerpoCeleste("Saturno", 9.53667594, -0.00125060,
      0.05386179, -0.00050991, 2.48599187, 0.00193609, 49.95424423, 1222.49362201,
      92.59887831, -0.41897216, 113.66242448, -0.28867794, 29.46,textureSaturn);
  const urano = new CuerpoCeleste("Urano", 19.18916464, -0.00196176, 0.04725744,
      -0.00004397, 0.77263783, -0.00242939, 313.23810451, 428.48202785, 170.95427630,
      0.40805281, 74.01692503, 0.04240589, 84.01, textureUranus);
  const neptuno = new CuerpoCeleste("Neptuno", 30.06952752, 0.00006447, 0.00895439, 0.00000818, 1.77005520, 0.00022400, 304.22289287, 218.46515314, 46.68158724, 0.01009938, 131.78635853, -0.00606302, 164.8,textureNeptune);
  const pluton = new CuerpoCeleste("Plutón", 39.76117, 0, 2.502879951216484e-01, 0, 1.732559807118311e+01, 0, 0, 0, 1.151409620637363E+02, 0, 1.104336423551854E+02, 0, 248.1,texturePluto);

  let planetas: CuerpoCeleste[] = [mercurio, venus, tierra, marte, jupiter, saturno, urano, neptuno, pluton]

  const planetPoints: Vector3[][] = []
  for (const planeta of planetas) {
    const points = [];
    for (const vec of planeta.calcTrajectory()) {
      points.push(new Vector3(vec[0], vec[1], vec[2]));
    }
    planetPoints.push(points);
  }

  let planetPositions: { planet: string; pos: Vector3;texture:AsyncWritable<Texture>  }[] = [];

  let cont = 0;
  const { start, stop, started, task } = useTask((delta) => {
    planetPositions = [];
    for (let planeta of planetas) {
      const pos = planeta.propagateOnTime(cont);
      planetPositions!.push({planet: planeta.name, pos: new Vector3(pos[0], pos[1], pos[2]), texture:planeta.texture});
    }
    cont += delta;
  })

  const sunPosArr: number[] = planetas[planetas.length -2].getSunPos();
  const sunPos: Vector3 = new Vector3(sunPosArr[0], sunPosArr[1], sunPosArr[2]);


</script>

<T.DirectionalLight position={[0, 10, 10]} />

{#each planetPoints as points}
<T.Mesh>
  <FakeGlowMaterial glowColor="red"/>
  <MeshLineGeometry {points} />
  <MeshLineMaterial
    width={0.125}
    color="#aaaaaa"
  />

</T.Mesh>
{/each}
<T.Mesh position={[sunPos.x, sunPos.y, sunPos.z]}>
  <T.SphereGeometry args={[1, 32, 32]} />
  <T.MeshBasicMaterial color="yellow" />
</T.Mesh>
<T.Mesh position={[sunPos.x, sunPos.y, sunPos.z]}>
	<FakeGlowMaterial glowColor="yellow"/>
    <T.IcosahedronGeometry args={[2, 4]} />
</T.Mesh>
{#each planetPositions as planeta}

  <T.Mesh position.x={planeta.pos.x} position.y={planeta.pos.y} position.z={planeta.pos.z}>
    <FakeGlowMaterial glowColor="red"/>
    <T.SphereGeometry args={[0.5, 16, 16]} />
    {#await planeta.texture then texture}
    <T.MeshStandardMaterial map={texture} />  
    {/await}  
  </T.Mesh>
{/each}
