<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/krunker_prp/Projects/orrery-space-apps/static/models/scene.gltf --root /models/ --types --printwidth 120 --precision 2
Author: valmirt (https://sketchfab.com/valmirt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-system-d3f058bbe20e4f70b2b52277ff8e109a
Title: Solar System
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import {OrbitControls} from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Sol1_lambert2_0: THREE.Mesh
      Sol1_lambert3_0: THREE.Mesh
      Sol1_lambert4_0: THREE.Mesh
      Sol1_lambert5_0: THREE.Mesh
      Sol1_lambert6_0: THREE.Mesh
      Sol1_lambert7_0: THREE.Mesh
      Sol1_lambert10_0: THREE.Mesh
      Sol1_lambert11_0: THREE.Mesh
      Sol1_lambert12_0: THREE.Mesh
      Sol1_lambert13_0: THREE.Mesh
      Sol1_lambert9_0: THREE.Mesh
    }
    materials: {
      lambert2: THREE.MeshBasicMaterial
      lambert3: THREE.MeshBasicMaterial
      lambert4: THREE.MeshBasicMaterial
      lambert5: THREE.MeshBasicMaterial
      lambert6: THREE.MeshBasicMaterial
      lambert7: THREE.MeshBasicMaterial
      lambert10: THREE.MeshBasicMaterial
      lambert11: THREE.MeshBasicMaterial
      lambert12: THREE.MeshBasicMaterial
      lambert13: THREE.MeshBasicMaterial
      lambert9: THREE.MeshBasicMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/scene.gltf')

  const component = forwardEventHandlers()
</script>

<T.PerspectiveCamera
  makeDefault
  position={[0, -1500, 0]}
  fov={50}
  far={10000}
>
  <OrbitControls
    autoRotate
    enableZoom={true}
    enableDamping
    autoRotateSpeed={0.0}
    target.y={1.5}
  />
</T.PerspectiveCamera>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Sol1_lambert2_0.geometry} material={gltf.materials.lambert2} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert3_0.geometry} material={gltf.materials.lambert3} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert4_0.geometry} material={gltf.materials.lambert4} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert5_0.geometry} material={gltf.materials.lambert5} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert6_0.geometry} material={gltf.materials.lambert6} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert7_0.geometry} material={gltf.materials.lambert7} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert10_0.geometry} material={gltf.materials.lambert10} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert11_0.geometry} material={gltf.materials.lambert11} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert12_0.geometry} material={gltf.materials.lambert12} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert13_0.geometry} material={gltf.materials.lambert13} />
    <T.Mesh geometry={gltf.nodes.Sol1_lambert9_0.geometry} material={gltf.materials.lambert9} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
